### ISSUE TITLE
todo for revision (5/29)

### ISSUE THREAD

**Issue by dyurovsky** [benjamincmorris/purple_carrots#1]
- [x] add details about word2vec @cbergey 
- [x] add a sentence about other potential cues to reference @benjamincmorris 
- [x] think about editing "Our model does capture meaningful information about the structure of language..." @benjamincmorris 
- [x] the authors should unpack the hypothesis that "children expect language to be used informatively at a young age." Is this expectation reasonable for, say, an 18-month-old? cite greenfield @cbergey 
- [x] adult atypicality might be more likely to get imitated by kids, bannard paper @benjamincmorris 
- [ ] add pre-registration @cbergey 
- [x] remove blinding @dyurovsky 
- [x] put on arxiv @dyurovsky 
- [x] link osf in paper @dyurovsky 
- [x] merge repos @cbergey

**Comment by benjamincmorris** [comment]
- [ ] final spell check
